### PR TITLE
V1.0

### PR DESCRIPTION
**Pull request by aaronhans**
This is an AWS Lambda cron which will review all pages on a site based on its sitemap and do lighthouse performance analysis. The perf score is recorded in dynamodb. 

This will be used as the source of ODI site live performance data to power the PAR display at the bottom of each page.

The full dataset will be retrieved by 11ty in a _data files function right before the page build runs.

This is setup to run synchronously which is slow but it is a cron that runs once a day to update the db, may have it run more frequently if that makes sense.

I didn't have this record historical performance data. We currently get that with nice graphs from calibre.

### CODE REVIEW

**Comment by xjensen** [comment]
Are there any organizational priorities that are driving this? Or is this primarily a cool thing that we want to do?

**Review by chachasikes — COMMENTED** [review]
Questions: 
- do we have any other internal documentation on the project overall?
- are there any access or service management keys or other things we might need in order to manage this. Is our standard access to AWS enough?

**Comment by aaronhans** [comment]
This service was created to power the performance measurement now displayed in the footer of all pages on the ODI site. 

The 11ty _data file calls the read endpoint on this service to get all the performance readings for the site at once during a build.

I think this addition to the site dovetails nicely with the equity order and ODI's mandate to provide training because we have seen deficiencies throughout the state in these metrics and the ODI team has the expertise to advise on how to make improvements.

Displaying the stats is cool because we are being transparent but you can see that there are links under each number to explain why that metric is important, how we determine it and how you can improve it in your own web service.

Screenshot 2023-05-19 at 3 52 24 PM

I created this as an external service when I discovered that I couldn't perform this audit fast enough using lighthouse to get it done during each production build. It takes several seconds for each page so would add over 10 minutes to the build for ODI's small site.

I tried several things when building this service starting with lighthouse as embedded in 11ty creator Zach Leatherman's <a href="https://www.npmjs.com/package/performance-leaderboard">performance-leaderboard</a> modules.

There were several problems running these tools which use lighthouse locally inside the AWS Lambda environment, some of them created bundles too large, the total runtime took too long. I ended up switching to making this hit google's lighthouse page speed API to get a reading instead. Unfortunately this analysis is not guaranteed to be performed from the US and we can't effectively warm the cache on ODI site's low traffic pages so you see slightly lower performance scores than what we get when we run lighthouse against the site using dev tools on our own machines but it is still a fair analysis.

If we were to expand this service in the future we might want to try:
- Going back to running lighthouse locally either directly or with performance-leaderboard instead of hitting the google pagespeed API
- Running this on a constantly available server instead of lambda so we aren't limited in total code bundle size and can run longer analyses safely

**Comment by zakiya** [comment]
@aaronhans Can you add your last comment to the project readme please?

**Comment by aaronhans** [comment]
readme updated

**Comment by zakiya** [comment]
Let's go ahead and merge this.

**Pull request merged**
